# AUTOGENERATED! DO NOT EDIT! File to edit: app.ipynb.

# %% auto 0
__all__ = ['path', 'learn', 'categories', 'examples', 'intf', 'classify_image']

# %% app.ipynb 0
from fastai.vision.all import PILImage, load_learner
import gradio as gr
import pathlib
path = pathlib.Path().absolute()

# %% app.ipynb 2
learn = load_learner(path/'model.pkl')

# %% app.ipynb 4
categories = learn.dls.vocab

def classify_image(img):
    pred,idx,probs = learn.predict(img)
    return dict(zip(categories, map(float,probs)))

# %% app.ipynb 6
examples = ['sample.png']
intf = gr.Interface(fn=classify_image, inputs="image", outputs="label", examples=examples, allow_flagging="never")
intf.launch(inline=False, share=True)


